server:
  port: 8100
spring:
  datasource:
    url: jdbc:mysql://47.113.190.57:3306/cloudstudy?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Abc1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: bookservice
eureka:
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka
